# Generated by Django 4.1.2 on 2023-01-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carrinho_compras',
            fields=[
                ('id_carrinho', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField()),
                ('preco_total', models.IntegerField()),
            ],
            options={
                'db_table': 'carrinho_compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='itens_carrinho_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_carrinho', models.IntegerField()),
                ('id_produto', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('nome_produto', models.CharField(max_length=255)),
                ('preco_produto', models.FloatField()),
                ('imagem_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('desconto_produto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'itens_carrinho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itens_Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_pedido', models.IntegerField()),
                ('id_produto', models.IntegerField()),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'db_table': 'itens_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='todos_pedidos_model',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=255)),
                ('data', models.DateField()),
            ],
            options={
                'db_table': 'pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('tipouser', models.CharField(max_length=100)),
                ('morada', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'utilizadores',
            },
        ),
    ]
