# Generated by Django 4.1.5 on 2023-01-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd2app', '0003_alter_user_managers_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
