# Generated by Django 4.1.2 on 2023-01-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd2app', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoFornecedor',
            fields=[
                ('id_pedidofornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('id_fornecedor', models.IntegerField()),
                ('id_produto', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('datapedido', models.DateTimeField()),
                ('dataentrega', models.DateTimeField()),
                ('estado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pedidos_fornecedor',
                'managed': False,
            },
        ),
    ]
