# Generated by Django 4.1.2 on 2023-02-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd2app', '0005_pedidofornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs_plpgsql',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('id_utilizador', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=255)),
                ('nome_tabela', models.CharField(max_length=255)),
                ('ids_tabela', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'logs_plpgsql',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='produtoMongo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('marca', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('imagem', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('stock', models.IntegerField()),
                ('desconto', models.FloatField()),
                ('categoria', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('id_utilizador', models.CharField(max_length=100)),
                ('belongs_store', models.CharField(max_length=100)),
            ],
        ),
    ]
